name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}
            base: header
            plugin_isocalendar: yes
            plugin_languages: yes
            plugin_topics: yes
            plugin_topics_limit: 0
            plugin_topics_mode: icons
            plugin_activity: yes
            plugin_activity_limit: 5
            plugin_activity_days: 0
            config_order: base.header, isocalendar, languages, topics, activity
