name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}
            base: header
            plugin_languages: yes
            plugin_topics: yes
            plugin_topics_limit: 0
            plugin_topics_mode: icons
            plugin_achievements: yes
            plugin_achievements_display: detailed
            plugin_achievements_secrets: yes
            plugin_achievements_threshold: C
            config_order: base.header, languages, topics, achievements
            config_display: columns
            config_timezone: Europe/London
