name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}
            base: header
            plugin_languages: yes
            plugin_topics: yes
            plugin_topics_limit: 0
            plugin_topics_mode: icons
            plugin_pagespeed: yes
            plugin_pagespeed_detailed: yes
            plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
            plugin_pagespeed_url: https://danmassarano.com
            config_order: base.header, languages, topics, pagespeed
